# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'video_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13video_service.proto\x12\x05video\"\x80\x01\n\rUploadRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\r\n\x05\x63hunk\x18\x03 \x01(\x0c\x12\x13\n\x0b\x63hunk_index\x18\x04 \x01(\x05\x12\x14\n\x0ctotal_chunks\x18\x05 \x01(\x05\x12\x11\n\tfile_type\x18\x06 \x01(\t\"\x84\x01\n\x0eUploadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x66ile_url\x18\x03 \x01(\t\x12\x17\n\x0fuploaded_chunks\x18\x04 \x01(\x05\x12\x14\n\x0ctotal_chunks\x18\x05 \x01(\x05\x12\x10\n\x08progress\x18\x06 \x01(\x02\"J\n\x11\x43reateTaskRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\timage_url\x18\x02 \x01(\t\x12\x11\n\tvideo_url\x18\x03 \x01(\t\"\x94\x01\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x05\x12\x12\n\nresult_url\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\"$\n\x11TaskStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"#\n\x10UserTasksRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"L\n\x11UserTasksResponse\x12\"\n\x05tasks\x18\x01 \x03(\x0b\x32\x13.video.TaskResponse\x12\x13\n\x0btotal_tasks\x18\x02 \x01(\x05\x32\x8e\x02\n\x0cVideoService\x12>\n\x0bUploadVideo\x12\x14.video.UploadRequest\x1a\x15.video.UploadResponse(\x01\x30\x01\x12;\n\nCreateTask\x12\x18.video.CreateTaskRequest\x1a\x13.video.TaskResponse\x12>\n\rGetTaskStatus\x12\x18.video.TaskStatusRequest\x1a\x13.video.TaskResponse\x12\x41\n\x0cGetUserTasks\x12\x17.video.UserTasksRequest\x1a\x18.video.UserTasksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=31
  _globals['_UPLOADREQUEST']._serialized_end=159
  _globals['_UPLOADRESPONSE']._serialized_start=162
  _globals['_UPLOADRESPONSE']._serialized_end=294
  _globals['_CREATETASKREQUEST']._serialized_start=296
  _globals['_CREATETASKREQUEST']._serialized_end=370
  _globals['_TASKRESPONSE']._serialized_start=373
  _globals['_TASKRESPONSE']._serialized_end=521
  _globals['_TASKSTATUSREQUEST']._serialized_start=523
  _globals['_TASKSTATUSREQUEST']._serialized_end=559
  _globals['_USERTASKSREQUEST']._serialized_start=561
  _globals['_USERTASKSREQUEST']._serialized_end=596
  _globals['_USERTASKSRESPONSE']._serialized_start=598
  _globals['_USERTASKSRESPONSE']._serialized_end=674
  _globals['_VIDEOSERVICE']._serialized_start=677
  _globals['_VIDEOSERVICE']._serialized_end=947
# @@protoc_insertion_point(module_scope)
